version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: spark_app_db_container
    restart: always
    environment:
      POSTGRES_DB: spark_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12344321
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: