version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: spark_db_dev
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - spark_network_dev

  redis:
    image: redis:7
    container_name: spark_redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - spark_network_dev

networks:
  spark_network_dev:
    driver: bridge

volumes:
  postgres_data_dev:
  redis_data_dev: