# Generated by Django 6.0.3 on 2026-03-28 11:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Birthday')),
                ('height', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Height')),
                ('weight', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Weight')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Username must start with a letter, be 3–20 characters long, can include letters, numbers, and underscores, and cannot contain double underscores (__).', regex='^(?!.*__)[A-Za-z][A-Za-z0-9_]{2,19}$')], verbose_name='Login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Joined')),
                ('last_active', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=255, verbose_name='Surname')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Last Name')),
                ('location', models.CharField(db_index=True, max_length=255, verbose_name='Location')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('additional_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.info')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='user.gender')),
                ('looking_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looking_for', to='user.gender')),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.interest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'unique_together': {('profile', 'interest')},
            },
        ),
    ]
