# Generated by Django 6.0.3 on 2026-03-27 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Birthday')),
                ('height', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Height')),
                ('weight', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Weight')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('education', models.TextField(blank=True, verbose_name='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Active'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=255, verbose_name='Surname')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Last Name')),
                ('location', models.CharField(db_index=True, max_length=255, verbose_name='Location')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('additional_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.info')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='user.gender')),
                ('looking_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='looking_for', to='user.gender')),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.interests')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'unique_together': {('profile', 'interest')},
            },
        ),
    ]
