# Generated by Django 6.0.3 on 2026-03-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_gender_info_interests_photos_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='ProfileInterests',
            new_name='ProfileInterest',
        ),
    ]
